// SFXR_DEFINE(Type, TYPE, Name)
SFXR_DEFINE(U32, U32, WaveType)

SFXR_DEFINE(Float, FLOAT, BaseFrequency)
SFXR_DEFINE(Float, FLOAT, FrequencyLimit)
SFXR_DEFINE(Float, FLOAT, FrequencyRamp)
SFXR_DEFINE(Float, FLOAT, FrequencyDeltaramp)

SFXR_DEFINE(Float, FLOAT, Duty)
SFXR_DEFINE(Float, FLOAT, DutyRamp)

SFXR_DEFINE(Float, FLOAT, VibratoStrength)
SFXR_DEFINE(Float, FLOAT, VibratoSpeed)

SFXR_DEFINE(Float, FLOAT, EnvelopeAttack)
SFXR_DEFINE(Float, FLOAT, EnvelopeSustain)
SFXR_DEFINE(Float, FLOAT, EnvelopeDecay)
SFXR_DEFINE(Float, FLOAT, EnvelopePunch)

SFXR_DEFINE(Float, FLOAT, LPFResonance)
SFXR_DEFINE(Float, FLOAT, LPFFrequency)
SFXR_DEFINE(Float, FLOAT, LPFRamp)

SFXR_DEFINE(Float, FLOAT, HPFFrequency)
SFXR_DEFINE(Float, FLOAT, HPFRamp)

SFXR_DEFINE(Float, FLOAT, PhaserOffset)
SFXR_DEFINE(Float, FLOAT, PhaserRamp)

SFXR_DEFINE(Float, FLOAT, RepeatSpeed)

SFXR_DEFINE(Float, FLOAT, ArpeggiationMod)
SFXR_DEFINE(Float, FLOAT, ArpeggiationSpeed)
